apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend
        app: frontend
    spec:
      nodeSelector:
        role: frontend
      containers:
        - env:
            - name: AUTH_API_ADDRESS
              value: http://auth-api.backend.svc.cluster.local:8000
            - name: PORT
              value: "8080"
            - name: TODOS_API_ADDRESS
              value: http://todos-api.backend.svc.cluster.local:8082
            - name: ZIPKIN_URL
              value: http://zipkin.monitoring.svc.cluster.local:9411/
          image: us-east4-docker.pkg.dev/arquisoftv-microservice-app/microservice-registry/frontend:latest
          name: frontend-container
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
