apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: backend
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: us-central1-docker.pkg.dev/arquisoftv-microservice-app/microservice-registry/users-api:latest
          imagePullPolicy: Always
          env:
            - name: JWT_SECRET
              value: PRFT
            - name: SERVER_PORT
              value: "8083"
            - name: ZIPKIN_URL
              value: http://zipkin.monitoring.svc.cluster.local:9411/
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
      nodeSelector:
        role: backend
