apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: backend
  labels:
    app: users-api
spec:
  selector:
    app: users-api
  ports:
    - name: http
      port: 8083
      targetPort: 8083
