apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: backend
  labels:
    app: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
