apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: monitoring
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: 9411
