apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: backend
  labels:
    app: todos-api
spec:
  selector:
    app: todos-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
