name: Deploy Manifests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: "${{ secrets.GCP_PROJECT }}"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ vars.GCP_ZONE }}

      - name: Apply all Kubernetes manifests
        run: |
          kubectl apply -R -f manifests/

      - id: get-pods
        run: |
          for ns in frontend backend database monitoring; do
            echo "📦 Pods in namespace: $ns"
            kubectl get pods -n "$ns"
            echo ""
          done
